### ISSUE TITLE
 illenium-appearance  EXPORT

### ISSUE THREAD

**Issue by allyaminou** [iLLeniumStudios/illenium-appearance#323]
We need an export that we can use for houses systems etc. 

I've tried the triggers and they won't work with my scripts. 
If someone can make an export that would be great !

**Comment by TheiLLeniumStudios** [comment]
`illenium-appearance:client:openOutfitMenu`

**Comment by mtlcity** [comment]
Hi is there an way to add an export for when I'm changing my clothes but my clothes won't change because ts_Busdriver script doesn't have a menu only a pop up that says press E to change clothes. do you have chance have an export for this? I keep getting this error 

"SCRIPT ERROR: @illenium-appearance/client/outfits-108:30: attempt to index a number value (field anus)"
